// A hand-curated list of common French grocery staples — the same idea Bring!
// uses for its core catalog. Open Food Facts only indexes barcoded packaged
// products, so a plain "pomme" or "oignon" almost never shows up there even
// though it's exactly what a shopping list needs. This list is checked first,
// instantly (no network), before falling back to Open Food Facts for branded
// / packaged items. Deliberately includes several phrasings per family (e.g.
// "Fromage râpé", "Fromage blanc", "Fromage de chèvre") so a broad search
// like "fromage" surfaces all of them, not just an exact-name match.
export const STAPLES = [
  // Fruits & légumes
  ['Pomme', 'fruits_legumes'],
  ['Poire', 'fruits_legumes'],
  ['Banane', 'fruits_legumes'],
  ['Orange', 'fruits_legumes'],
  ['Clémentine', 'fruits_legumes'],
  ['Mandarine', 'fruits_legumes'],
  ['Citron', 'fruits_legumes'],
  ['Citron vert', 'fruits_legumes'],
  ['Pamplemousse', 'fruits_legumes'],
  ['Fraise', 'fruits_legumes'],
  ['Framboise', 'fruits_legumes'],
  ['Myrtille', 'fruits_legumes'],
  ['Mûre', 'fruits_legumes'],
  ['Groseille', 'fruits_legumes'],
  ['Cassis', 'fruits_legumes'],
  ['Raisin', 'fruits_legumes'],
  ['Pêche', 'fruits_legumes'],
  ['Nectarine', 'fruits_legumes'],
  ['Abricot', 'fruits_legumes'],
  ['Prune', 'fruits_legumes'],
  ['Mirabelle', 'fruits_legumes'],
  ['Cerise', 'fruits_legumes'],
  ['Melon', 'fruits_legumes'],
  ['Pastèque', 'fruits_legumes'],
  ['Ananas', 'fruits_legumes'],
  ['Mangue', 'fruits_legumes'],
  ['Kiwi', 'fruits_legumes'],
  ['Avocat', 'fruits_legumes'],
  ['Figue', 'fruits_legumes'],
  ['Datte', 'fruits_legumes'],
  ['Grenade', 'fruits_legumes'],
  ['Litchi', 'fruits_legumes'],
  ['Fruit de la passion', 'fruits_legumes'],
  ['Papaye', 'fruits_legumes'],
  ['Goyave', 'fruits_legumes'],
  ['Coing', 'fruits_legumes'],
  ['Kaki', 'fruits_legumes'],
  ['Rhubarbe', 'fruits_legumes'],
  ['Noix de coco', 'fruits_legumes'],
  ['Tomate', 'fruits_legumes'],
  ['Tomate cerise', 'fruits_legumes'],
  ['Concombre', 'fruits_legumes'],
  ['Salade', 'fruits_legumes'],
  ['Laitue', 'fruits_legumes'],
  ['Mâche', 'fruits_legumes'],
  ['Roquette', 'fruits_legumes'],
  ['Cresson', 'fruits_legumes'],
  ['Endive', 'fruits_legumes'],
  ['Carotte', 'fruits_legumes'],
  ['Pomme de terre', 'fruits_legumes'],
  ['Patate douce', 'fruits_legumes'],
  ['Oignon', 'fruits_legumes'],
  ['Oignon rouge', 'fruits_legumes'],
  ['Oignon blanc', 'fruits_legumes'],
  ['Oignon nouveau', 'fruits_legumes'],
  ['Ail', 'fruits_legumes'],
  ['Échalote', 'fruits_legumes'],
  ['Poireau', 'fruits_legumes'],
  ['Courgette', 'fruits_legumes'],
  ['Aubergine', 'fruits_legumes'],
  ['Poivron', 'fruits_legumes'],
  ['Piment', 'fruits_legumes'],
  ['Champignon', 'fruits_legumes'],
  ['Champignon de Paris', 'fruits_legumes'],
  ['Brocoli', 'fruits_legumes'],
  ['Chou-fleur', 'fruits_legumes'],
  ['Chou', 'fruits_legumes'],
  ['Chou rouge', 'fruits_legumes'],
  ['Chou vert', 'fruits_legumes'],
  ['Chou de Bruxelles', 'fruits_legumes'],
  ['Épinard', 'fruits_legumes'],
  ['Haricot vert', 'fruits_legumes'],
  ['Petit pois', 'fruits_legumes'],
  ['Fève', 'fruits_legumes'],
  ['Radis', 'fruits_legumes'],
  ['Céleri', 'fruits_legumes'],
  ['Céleri-rave', 'fruits_legumes'],
  ['Betterave', 'fruits_legumes'],
  ['Navet', 'fruits_legumes'],
  ['Panais', 'fruits_legumes'],
  ['Topinambour', 'fruits_legumes'],
  ['Potiron', 'fruits_legumes'],
  ['Courge butternut', 'fruits_legumes'],
  ['Fenouil', 'fruits_legumes'],
  ['Asperge', 'fruits_legumes'],
  ['Artichaut', 'fruits_legumes'],
  ['Maïs frais', 'fruits_legumes'],
  ['Persil', 'fruits_legumes'],
  ['Basilic', 'fruits_legumes'],
  ['Menthe', 'fruits_legumes'],
  ['Coriandre', 'fruits_legumes'],
  ['Ciboulette', 'fruits_legumes'],
  ['Thym', 'fruits_legumes'],
  ['Romarin', 'fruits_legumes'],
  ['Gingembre', 'fruits_legumes'],

  // Produits laitiers
  ['Lait', 'produits_laitiers'],
  ['Lait demi-écrémé', 'produits_laitiers'],
  ['Lait entier', 'produits_laitiers'],
  ['Lait écrémé', 'produits_laitiers'],
  ['Lait ribot', 'produits_laitiers'],
  ['Lait fermenté', 'produits_laitiers'],
  ['Babeurre', 'produits_laitiers'],
  ['Beurre', 'produits_laitiers'],
  ['Beurre doux', 'produits_laitiers'],
  ['Beurre salé', 'produits_laitiers'],
  ['Crème fraîche', 'produits_laitiers'],
  ['Crème liquide', 'produits_laitiers'],
  ['Crème épaisse', 'produits_laitiers'],
  ['Crème entière', 'produits_laitiers'],
  ['Yaourt', 'produits_laitiers'],
  ['Yaourt nature', 'produits_laitiers'],
  ['Yaourt aux fruits', 'produits_laitiers'],
  ['Yaourt grec', 'produits_laitiers'],
  ['Yaourt à boire', 'produits_laitiers'],
  ['Yaourt brassé', 'produits_laitiers'],
  ['Skyr', 'produits_laitiers'],
  ['Fromage', 'produits_laitiers'],
  ['Fromage blanc', 'produits_laitiers'],
  ['Fromage râpé', 'produits_laitiers'],
  ['Fromage de chèvre', 'produits_laitiers'],
  ['Fromage de brebis', 'produits_laitiers'],
  ['Fromage à tartiner', 'produits_laitiers'],
  ['Fromage à raclette', 'produits_laitiers'],
  ['Fromage à fondue', 'produits_laitiers'],
  ['Fromage frais', 'produits_laitiers'],
  ['Fromage fondu', 'produits_laitiers'],
  ['Fromage en tranches', 'produits_laitiers'],
  ['Fromage en portions', 'produits_laitiers'],
  ['Camembert', 'produits_laitiers'],
  ['Comté', 'produits_laitiers'],
  ['Emmental', 'produits_laitiers'],
  ['Mozzarella', 'produits_laitiers'],
  ['Parmesan', 'produits_laitiers'],
  ['Chèvre', 'produits_laitiers'],
  ['Roquefort', 'produits_laitiers'],
  ['Brie', 'produits_laitiers'],
  ['Cantal', 'produits_laitiers'],
  ['Reblochon', 'produits_laitiers'],
  ['Munster', 'produits_laitiers'],
  ['Bleu', 'produits_laitiers'],
  ['Feta', 'produits_laitiers'],
  ['Ricotta', 'produits_laitiers'],
  ['Boursin', 'produits_laitiers'],
  ['Faisselle', 'produits_laitiers'],
  ['Œufs', 'produits_laitiers'],
  ['Petit-suisse', 'produits_laitiers'],
  ['Margarine', 'produits_laitiers'],
  ['Crème dessert', 'produits_laitiers'],

  // Viande & poisson
  ['Poulet', 'viande_poisson'],
  ['Blanc de poulet', 'viande_poisson'],
  ['Escalope de poulet', 'viande_poisson'],
  ['Filet de poulet', 'viande_poisson'],
  ['Cuisse de poulet', 'viande_poisson'],
  ['Aile de poulet', 'viande_poisson'],
  ['Nuggets de poulet', 'viande_poisson'],
  ['Cordon bleu', 'viande_poisson'],
  ['Bœuf', 'viande_poisson'],
  ['Steak haché', 'viande_poisson'],
  ['Rôti de bœuf', 'viande_poisson'],
  ['Côte de bœuf', 'viande_poisson'],
  ['Entrecôte', 'viande_poisson'],
  ['Bavette', 'viande_poisson'],
  ['Faux-filet', 'viande_poisson'],
  ['Viande à bourguignon', 'viande_poisson'],
  ['Porc', 'viande_poisson'],
  ['Côte de porc', 'viande_poisson'],
  ['Rôti de porc', 'viande_poisson'],
  ['Filet mignon', 'viande_poisson'],
  ['Travers de porc', 'viande_poisson'],
  ['Jambon', 'viande_poisson'],
  ['Jambon blanc', 'viande_poisson'],
  ['Jambon cru', 'viande_poisson'],
  ['Jambon fumé', 'viande_poisson'],
  ['Saucisse', 'viande_poisson'],
  ['Saucisson', 'viande_poisson'],
  ['Chorizo', 'viande_poisson'],
  ['Lardons', 'viande_poisson'],
  ['Bacon', 'viande_poisson'],
  ['Merguez', 'viande_poisson'],
  ['Pâté', 'viande_poisson'],
  ['Rillettes', 'viande_poisson'],
  ['Boudin', 'viande_poisson'],
  ['Foie gras', 'viande_poisson'],
  ['Agneau', 'viande_poisson'],
  ['Gigot d\'agneau', 'viande_poisson'],
  ['Dinde', 'viande_poisson'],
  ['Escalope de dinde', 'viande_poisson'],
  ['Canard', 'viande_poisson'],
  ['Magret de canard', 'viande_poisson'],
  ['Lapin', 'viande_poisson'],
  ['Saumon', 'viande_poisson'],
  ['Saumon fumé', 'viande_poisson'],
  ['Thon', 'viande_poisson'],
  ['Thon en boîte', 'viande_poisson'],
  ['Cabillaud', 'viande_poisson'],
  ['Truite', 'viande_poisson'],
  ['Sardine', 'viande_poisson'],
  ['Maquereau', 'viande_poisson'],
  ['Dorade', 'viande_poisson'],
  ['Bar', 'viande_poisson'],
  ['Sole', 'viande_poisson'],
  ['Colin', 'viande_poisson'],
  ['Merlan', 'viande_poisson'],
  ['Anchois', 'viande_poisson'],
  ['Crevettes', 'viande_poisson'],
  ['Moules', 'viande_poisson'],
  ['Huîtres', 'viande_poisson'],
  ['Calamar', 'viande_poisson'],
  ['Poulpe', 'viande_poisson'],
  ['Coquilles Saint-Jacques', 'viande_poisson'],
  ['Surimi', 'viande_poisson'],
  ['Tarama', 'viande_poisson'],
  ['Poisson pané', 'viande_poisson'],
  ['Tofu', 'viande_poisson'],
  ['Steak végétal', 'viande_poisson'],

  // Épicerie
  ['Pâtes', 'epicerie'],
  ['Pâtes complètes', 'epicerie'],
  ['Spaghetti', 'epicerie'],
  ['Nouilles', 'epicerie'],
  ['Riz', 'epicerie'],
  ['Riz basmati', 'epicerie'],
  ['Riz rond', 'epicerie'],
  ['Semoule', 'epicerie'],
  ['Couscous', 'epicerie'],
  ['Boulgour', 'epicerie'],
  ['Quinoa', 'epicerie'],
  ['Farine', 'epicerie'],
  ['Farine complète', 'epicerie'],
  ['Farine de sarrasin', 'epicerie'],
  ['Sucre', 'epicerie'],
  ['Sucre roux', 'epicerie'],
  ['Sucre glace', 'epicerie'],
  ['Sucre vanillé', 'epicerie'],
  ['Édulcorant', 'epicerie'],
  ['Sel', 'epicerie'],
  ['Gros sel', 'epicerie'],
  ['Fleur de sel', 'epicerie'],
  ['Poivre', 'epicerie'],
  ["Huile d'olive", 'epicerie'],
  ['Huile de tournesol', 'epicerie'],
  ['Huile de colza', 'epicerie'],
  ['Huile de coco', 'epicerie'],
  ['Huile de sésame', 'epicerie'],
  ['Vinaigre', 'epicerie'],
  ['Vinaigre balsamique', 'epicerie'],
  ['Vinaigre de cidre', 'epicerie'],
  ['Moutarde', 'epicerie'],
  ['Mayonnaise', 'epicerie'],
  ['Ketchup', 'epicerie'],
  ['Sauce barbecue', 'epicerie'],
  ['Sauce curry', 'epicerie'],
  ['Sauce pesto', 'epicerie'],
  ['Sauce tomate', 'epicerie'],
  ['Coulis de tomate', 'epicerie'],
  ['Tomates pelées', 'epicerie'],
  ['Concentré de tomate', 'epicerie'],
  ['Tapenade', 'epicerie'],
  ['Houmous', 'epicerie'],
  ['Guacamole', 'epicerie'],
  ['Câpres', 'epicerie'],
  ['Cornichons', 'epicerie'],
  ['Olives', 'epicerie'],
  ['Lentilles', 'epicerie'],
  ['Pois chiches', 'epicerie'],
  ['Haricots blancs', 'epicerie'],
  ['Maïs en boîte', 'epicerie'],
  ['Petits pois en boîte', 'epicerie'],
  ['Champignons en boîte', 'epicerie'],
  ['Ravioli en boîte', 'epicerie'],
  ['Cassoulet', 'epicerie'],
  ['Céréales', 'epicerie'],
  ['Muesli', 'epicerie'],
  ["Flocons d'avoine", 'epicerie'],
  ['Porridge', 'epicerie'],
  ['Confiture', 'epicerie'],
  ['Miel', 'epicerie'],
  ['Sirop d\'érable', 'epicerie'],
  ['Pâte à tartiner', 'epicerie'],
  ['Chocolat', 'epicerie'],
  ['Chocolat noir', 'epicerie'],
  ['Chocolat au lait', 'epicerie'],
  ['Chocolat en poudre', 'epicerie'],
  ['Café', 'epicerie'],
  ['Café moulu', 'epicerie'],
  ['Café en grains', 'epicerie'],
  ['Capsules de café', 'epicerie'],
  ['Thé', 'epicerie'],
  ['Thé vert', 'epicerie'],
  ['Infusion', 'epicerie'],
  ['Levure', 'epicerie'],
  ['Levure chimique', 'epicerie'],
  ['Levure de boulanger', 'epicerie'],
  ['Bicarbonate de soude', 'epicerie'],
  ['Fécule de maïs', 'epicerie'],
  ['Chapelure', 'epicerie'],
  ['Bouillon cube', 'epicerie'],
  ['Fond de veau', 'epicerie'],
  ['Herbes de Provence', 'epicerie'],
  ['Épices', 'epicerie'],
  ['Chips', 'epicerie'],
  ['Biscuits', 'epicerie'],
  ['Gâteaux apéritifs', 'epicerie'],
  ['Crackers', 'epicerie'],
  ['Pop-corn', 'epicerie'],
  ['Compote', 'epicerie'],
  ['Soupe', 'epicerie'],
  ['Sauce soja', 'epicerie'],
  ['Vinaigrette', 'epicerie'],
  ['Cacahuètes', 'epicerie'],
  ['Amandes', 'epicerie'],
  ['Noix', 'epicerie'],
  ['Noisettes', 'epicerie'],
  ['Pistaches', 'epicerie'],
  ['Raisins secs', 'epicerie'],
  ['Pâte à tarte', 'epicerie'],
  ['Pâte feuilletée', 'epicerie'],
  ['Pâte brisée', 'epicerie'],
  ['Pâte sablée', 'epicerie'],
  ['Barre chocolatée', 'epicerie'],
  ['Bonbons', 'epicerie'],
  ['Chewing-gum', 'epicerie'],

  // Surgelés
  ['Frites surgelées', 'surgeles'],
  ['Légumes surgelés', 'surgeles'],
  ['Fruits surgelés', 'surgeles'],
  ['Pizza surgelée', 'surgeles'],
  ['Gratin surgelé', 'surgeles'],
  ['Glace', 'surgeles'],
  ['Sorbet', 'surgeles'],
  ['Glaçons', 'surgeles'],
  ['Poisson surgelé', 'surgeles'],
  ['Crevettes surgelées', 'surgeles'],
  ['Steak haché surgelé', 'surgeles'],
  ['Petits pois surgelés', 'surgeles'],
  ['Épinards surgelés', 'surgeles'],
  ['Nuggets surgelés', 'surgeles'],
  ['Viennoiserie surgelée', 'surgeles'],
  ['Quenelles', 'surgeles'],

  // Boulangerie
  ['Pain', 'boulangerie'],
  ['Baguette', 'boulangerie'],
  ['Pain complet', 'boulangerie'],
  ['Pain de campagne', 'boulangerie'],
  ['Pain de mie', 'boulangerie'],
  ['Pain aux céréales', 'boulangerie'],
  ['Pain de seigle', 'boulangerie'],
  ['Pain viennois', 'boulangerie'],
  ['Pain burger', 'boulangerie'],
  ['Pain pita', 'boulangerie'],
  ['Tortilla wrap', 'boulangerie'],
  ['Bagel', 'boulangerie'],
  ['Croissant', 'boulangerie'],
  ['Pain au chocolat', 'boulangerie'],
  ['Chausson aux pommes', 'boulangerie'],
  ['Brioche', 'boulangerie'],
  ['Biscotte', 'boulangerie'],
  ['Crêpe', 'boulangerie'],
  ['Galette', 'boulangerie'],
  ['Muffin', 'boulangerie'],
  ['Cookie', 'boulangerie'],
  ['Tarte', 'boulangerie'],
  ['Éclair', 'boulangerie'],

  // Boissons
  ['Eau', 'boissons'],
  ['Eau gazeuse', 'boissons'],
  ["Jus d'orange", 'boissons'],
  ['Jus de pomme', 'boissons'],
  ['Jus de raisin', 'boissons'],
  ['Jus multifruits', 'boissons'],
  ['Soda', 'boissons'],
  ['Coca-Cola', 'boissons'],
  ['Limonade', 'boissons'],
  ['Sirop', 'boissons'],
  ['Thé glacé', 'boissons'],
  ['Boisson énergisante', 'boissons'],
  ['Vin rouge', 'boissons'],
  ['Vin blanc', 'boissons'],
  ['Rosé', 'boissons'],
  ['Champagne', 'boissons'],
  ['Cidre', 'boissons'],
  ['Bière', 'boissons'],
  ['Whisky', 'boissons'],
  ['Vodka', 'boissons'],
  ['Rhum', 'boissons'],
  ['Lait végétal', 'boissons'],
  ["Lait d'amande", 'boissons'],
  ['Lait de soja', 'boissons'],
  ['Lait de coco', 'boissons'],
  ["Lait d'avoine", 'boissons'],

  // Hygiène & beauté
  ['Papier toilette', 'hygiene'],
  ['Mouchoirs', 'hygiene'],
  ['Savon', 'hygiene'],
  ['Gel douche', 'hygiene'],
  ['Bain moussant', 'hygiene'],
  ['Shampoing', 'hygiene'],
  ['Après-shampoing', 'hygiene'],
  ['Dentifrice', 'hygiene'],
  ['Brosse à dents', 'hygiene'],
  ['Fil dentaire', 'hygiene'],
  ['Bain de bouche', 'hygiene'],
  ['Déodorant', 'hygiene'],
  ['Rasoir', 'hygiene'],
  ['Mousse à raser', 'hygiene'],
  ['Après-rasage', 'hygiene'],
  ['Coton-tige', 'hygiene'],
  ['Coton démaquillant', 'hygiene'],
  ['Lingettes démaquillantes', 'hygiene'],
  ['Serviettes hygiéniques', 'hygiene'],
  ['Tampons', 'hygiene'],
  ['Protège-slips', 'hygiene'],
  ['Préservatifs', 'hygiene'],
  ['Crème hydratante', 'hygiene'],
  ['Crème pour les mains', 'hygiene'],
  ['Crème solaire', 'hygiene'],
  ['Baume à lèvres', 'hygiene'],
  ['Sparadrap', 'hygiene'],
  ['Pansement', 'hygiene'],

  // Entretien maison
  ['Liquide vaisselle', 'entretien'],
  ['Pastilles lave-vaisselle', 'entretien'],
  ['Sel régénérant', 'entretien'],
  ['Éponge', 'entretien'],
  ['Chiffon', 'entretien'],
  ['Gants de ménage', 'entretien'],
  ['Lessive', 'entretien'],
  ['Adoucissant', 'entretien'],
  ['Sac poubelle', 'entretien'],
  ['Papier essuie-tout', 'entretien'],
  ['Nettoyant multi-usage', 'entretien'],
  ['Nettoyant sol', 'entretien'],
  ['Nettoyant WC', 'entretien'],
  ['Nettoyant vitres', 'entretien'],
  ["Eau de javel", 'entretien'],
  ['Détartrant', 'entretien'],
  ['Anti-calcaire', 'entretien'],
  ['Désodorisant', 'entretien'],
  ['Insecticide', 'entretien'],
  ['Ampoule', 'entretien'],
  ['Pile', 'entretien'],
  ['Allumettes', 'entretien'],
  ['Bougie', 'entretien'],
  ['Film alimentaire', 'entretien'],
  ['Papier aluminium', 'entretien'],
  ['Papier cuisson', 'entretien'],
  ['Sac congélation', 'entretien'],
  ['Sac aspirateur', 'entretien'],

  // Bébé
  ['Couches', 'bebe'],
  ['Lait infantile', 'bebe'],
  ['Lait 1er âge', 'bebe'],
  ['Lait 2e âge', 'bebe'],
  ['Petit pot bébé', 'bebe'],
  ['Petit pot légumes', 'bebe'],
  ['Petit pot fruits', 'bebe'],
  ['Compote bébé', 'bebe'],
  ['Biscuits bébé', 'bebe'],
  ['Lingettes bébé', 'bebe'],
  ['Crème de change', 'bebe'],

  // Animaux
  ['Croquettes chien', 'animaux'],
  ['Croquettes chat', 'animaux'],
  ['Pâtée chat', 'animaux'],
  ['Pâtée chien', 'animaux'],
  ['Friandises chien', 'animaux'],
  ['Friandises chat', 'animaux'],
  ['Litière', 'animaux'],
].map(([name, category]) => ({ name, category, source: 'staple' }))

function normalize(str) {
  return str
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
}

/** Instant, offline, substring match over the curated staples list. */
export function searchStaples(query) {
  const q = normalize(query.trim())
  if (!q) return []
  return STAPLES.filter((s) => normalize(s.name).includes(q))
}
